"""Phase 8: configuration drift evidence and the Purview/Compliance binding.

Adds the two certificate-authentication columns Connect-IPPSSession needs, the
declared scalar factprint projection table, and the four drift tables (baseline,
run, event, notification). Every new datetime column is timestamptz: the Phase 6
naive-timestamp defect is real on a non-UTC database server, and Phase 8 must not
add another naive timestamp to this schema.

Nothing here can move a rating. drift_notification carries summary counts and no
value column at all, and drift_event's value columns are constrained to short
scalars so a raw tenant record cannot be stored even by a future bug.

Written by hand rather than autogenerated: alembic/env.py configures neither
compare_type nor include_object and cannot see triggers, so autogenerate output
would silently drop the guards below.

Forward-only, consistent with Phase 3/5/6/7.

Revision ID: a3f5c1d90b47
Revises: f7d2c48b1a03
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

revision = "a3f5c1d90b47"
down_revision = "f7d2c48b1a03"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # Certificate authentication for Connect-IPPSSession (D-P8-04).
    #
    # Both nullable and without a server default: an existing connection has
    # neither, and a missing value must stay missing rather than become an
    # invented one. No CHECK here either — the alias and the .onmicrosoft.com
    # organization grammar are validated in the Pydantic schema, which is the
    # only place that can return a useful message naming the expected form.
    #
    # Neither column is added to scan, scan_result or scan_dispatch, so
    # tools/ci/container_smoke.py's literal INSERT column lists stay valid.
    # ------------------------------------------------------------------
    op.add_column(
        "m365_connection",
        sa.Column("compliance_certificate_alias", sa.String(255), nullable=True),
    )
    op.add_column(
        "m365_connection",
        sa.Column("compliance_organization", sa.String(255), nullable=True),
    )

    # ------------------------------------------------------------------
    # Declared scalar projections of collector output (D-P8-07).
    #
    # What is persisted is a declared projection, never the raw collector
    # payload: bool / int / enum scalars and bounded enum sets. The CHECKs make
    # that structural — an object or an array can never be stored in
    # observed_value, and a set can never exceed its declared bound.
    # ------------------------------------------------------------------
    op.create_table(
        "scan_result_factprint",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("control_id", sa.String(50), nullable=False),
        sa.Column("collector_id", sa.String(120), nullable=False),
        sa.Column("projection_id", sa.String(120), nullable=False),
        sa.Column("field_name", sa.String(40), nullable=False),
        sa.Column("field_kind", sa.String(10), nullable=False),
        sa.Column("value_digest", sa.String(64), nullable=False),
        sa.Column("member_digests", JSONB(), nullable=True),
        sa.Column("member_tokens", JSONB(), nullable=True),
        sa.Column("observed_value", JSONB(), nullable=True),
        sa.Column("factprint_schema", sa.String(40), nullable=False),
        sa.Column("key_id", sa.String(16), nullable=False),
        sa.Column("retention_policy_version", sa.String(40), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scan.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "field_kind IN ('bool','int','enum','enum_set')",
            name="ck_factprint_field_kind",
        ),
        sa.CheckConstraint(
            "field_name ~ '^[a-z][a-z0-9_]{0,39}$'",
            name="ck_factprint_field_name",
        ),
        sa.CheckConstraint(
            "value_digest ~ '^[0-9a-f]{64}$'",
            name="ck_factprint_value_digest",
        ),
        sa.CheckConstraint(
            "observed_value IS NULL"
            " OR jsonb_typeof(observed_value) NOT IN ('object','array')",
            name="ck_factprint_scalar_value",
        ),
        sa.CheckConstraint(
            "observed_value IS NULL OR length(observed_value::text) <= 40",
            name="ck_factprint_value_length",
        ),
        sa.CheckConstraint(
            "(field_kind = 'enum_set') = (member_digests IS NOT NULL)",
            name="ck_factprint_set_members",
        ),
        sa.CheckConstraint(
            "(field_kind = 'enum_set') = (member_tokens IS NOT NULL)",
            name="ck_factprint_set_tokens",
        ),
        sa.CheckConstraint(
            "field_kind <> 'enum_set' OR observed_value IS NULL",
            name="ck_factprint_set_scalar",
        ),
        sa.CheckConstraint(
            "member_digests IS NULL OR jsonb_typeof(member_digests) = 'array'",
            name="ck_factprint_members_array",
        ),
        sa.CheckConstraint(
            "member_tokens IS NULL OR jsonb_typeof(member_tokens) = 'array'",
            name="ck_factprint_tokens_array",
        ),
        sa.CheckConstraint(
            "member_digests IS NULL OR jsonb_array_length(member_digests) <= 25",
            name="ck_factprint_members_bounded",
        ),
        sa.CheckConstraint(
            "member_tokens IS NULL OR jsonb_array_length(member_tokens) <= 25",
            name="ck_factprint_tokens_bounded",
        ),
    )
    op.create_index(
        "uq_factprint_scan_control_field",
        "scan_result_factprint",
        ["scan_id", "control_id", "field_name"],
        unique=True,
    )
    op.create_index("ix_factprint_scan_id", "scan_result_factprint", ["scan_id"])
    op.create_index("ix_factprint_control_id", "scan_result_factprint", ["control_id"])

    # ------------------------------------------------------------------
    # Drift baselines (D-P8-08).
    #
    # configuration_key and evaluation_key are digests over the whole
    # comparability tuple and are the baseline LOOKUP key, so comparing two
    # incomparable scans is structurally impossible rather than merely checked.
    # The baseline's scan is ON DELETE RESTRICT: an established baseline pins
    # the observation it was established from.
    # ------------------------------------------------------------------
    op.create_table(
        "drift_baseline",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("m365_connection_id", sa.Integer(), nullable=True),
        sa.Column("framework", sa.String(50), nullable=False),
        sa.Column("benchmark", sa.String(100), nullable=False),
        sa.Column("version", sa.String(20), nullable=False),
        sa.Column("metadata_digest", sa.String(64), nullable=False),
        sa.Column("policy_corpus_digest", sa.String(64), nullable=False),
        sa.Column("semantics_version", sa.String(30), nullable=False),
        sa.Column("connection_identity_digest", sa.String(64), nullable=False),
        sa.Column("configuration_key", sa.String(64), nullable=False),
        sa.Column("evaluation_key", sa.String(64), nullable=False),
        sa.Column("observation_digest", sa.String(64), nullable=False),
        sa.Column("control_count", sa.Integer(), nullable=False),
        sa.Column("factprint_field_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("superseded_by_id", sa.BigInteger(), nullable=True),
        sa.Column("established_by_user_id", sa.Integer(), nullable=True),
        sa.Column("drift_version", sa.String(30), nullable=False),
        sa.Column("retention_policy_version", sa.String(40), nullable=False),
        # The fingerprint key the baseline's facts were produced under. Null when
        # no key was configured. A later scan under a DIFFERENT key cannot be
        # compared on the configuration axis: every value_digest is an HMAC, so a
        # rotation would otherwise manufacture a changed event for every fact
        # against a tenant nobody touched.
        sa.Column("key_id", sa.String(16), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("established_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scan_id"], ["scan.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["m365_connection_id"], ["m365_connection.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"], ["drift_baseline.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["established_by_user_id"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "status IN ('active','superseded','revoked')",
            name="ck_drift_baseline_status",
        ),
        sa.CheckConstraint(
            "(status = 'superseded') = (superseded_at IS NOT NULL)",
            name="ck_drift_baseline_superseded",
        ),
        sa.CheckConstraint(
            "superseded_by_id IS NULL OR superseded_by_id <> id",
            name="ck_drift_baseline_supersede_self",
        ),
        sa.CheckConstraint(
            "note IS NULL OR length(note) <= 500",
            name="ck_drift_baseline_note_length",
        ),
        sa.CheckConstraint(
            "control_count >= 0", name="ck_drift_baseline_control_count"
        ),
        sa.CheckConstraint(
            "factprint_field_count >= 0", name="ck_drift_baseline_field_count"
        ),
    )
    op.create_index(
        "uq_drift_baseline_scan", "drift_baseline", ["scan_id"], unique=True
    )
    # At most one active baseline per comparability tuple, enforced by a partial
    # unique index rather than by application convention.
    op.create_index(
        "uq_drift_baseline_active_configuration",
        "drift_baseline",
        ["configuration_key"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index("ix_drift_baseline_user_id", "drift_baseline", ["user_id"])

    # ------------------------------------------------------------------
    # Drift runs.
    #
    # A run always records both comparability axes and why. Events exist only on
    # a completed run; a not-comparable or fingerprint-less run reports zero
    # events, which never means the tenant did not change.
    # ------------------------------------------------------------------
    op.create_table(
        "drift_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("baseline_id", sa.BigInteger(), nullable=False),
        sa.Column("baseline_scan_id", sa.Integer(), nullable=True),
        sa.Column("current_scan_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("framework", sa.String(50), nullable=False),
        sa.Column("benchmark", sa.String(100), nullable=False),
        sa.Column("version", sa.String(20), nullable=False),
        sa.Column("status", sa.String(30), nullable=False),
        sa.Column("trigger", sa.String(24), nullable=False),
        sa.Column("configuration_comparable", sa.Boolean(), nullable=False),
        sa.Column("evaluation_comparable", sa.Boolean(), nullable=False),
        sa.Column("axis_reasons", JSONB(), nullable=False),
        sa.Column("baseline_configuration_key", sa.String(64), nullable=False),
        sa.Column("current_configuration_key", sa.String(64), nullable=False),
        sa.Column("baseline_evaluation_key", sa.String(64), nullable=False),
        sa.Column("current_evaluation_key", sa.String(64), nullable=False),
        sa.Column("baseline_observation_digest", sa.String(64), nullable=True),
        sa.Column("current_observation_digest", sa.String(64), nullable=True),
        sa.Column("baseline_engine_source_digest", sa.String(64), nullable=True),
        sa.Column("current_engine_source_digest", sa.String(64), nullable=True),
        sa.Column("engine_changed", sa.Boolean(), nullable=True),
        sa.Column("controls_compared", sa.Integer(), nullable=False),
        sa.Column("controls_skipped", JSONB(), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("event_counts", JSONB(), nullable=False),
        sa.Column("event_set_digest", sa.String(64), nullable=False),
        sa.Column("key_id", sa.String(16), nullable=True),
        sa.Column("drift_version", sa.String(30), nullable=False),
        sa.Column("retention_policy_version", sa.String(40), nullable=False),
        sa.Column("correlation_id", sa.String(128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_id"], ["drift_baseline.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["baseline_scan_id"], ["scan.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["current_scan_id"], ["scan.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "status IN ('completed','not_comparable','fingerprints_unavailable',"
            "'event_limit_exceeded')",
            name="ck_drift_run_status",
        ),
        sa.CheckConstraint(
            "trigger IN ('scan_finalised','api_request')",
            name="ck_drift_run_trigger",
        ),
        sa.CheckConstraint(
            "(status = 'completed') OR event_count = 0",
            name="ck_drift_run_events_only_when_completed",
        ),
        sa.CheckConstraint(
            "(status IN ('not_comparable','fingerprints_unavailable'))"
            " = (NOT configuration_comparable AND NOT evaluation_comparable)",
            name="ck_drift_run_not_comparable",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(axis_reasons) = 'object'",
            name="ck_drift_run_axis_reasons",
        ),
        sa.CheckConstraint(
            "event_count >= 0 AND controls_compared >= 0",
            name="ck_drift_run_counts",
        ),
    )
    op.create_index(
        "uq_drift_run_baseline_scan",
        "drift_run",
        ["baseline_id", "current_scan_id"],
        unique=True,
    )
    op.create_index("ix_drift_run_user_id", "drift_run", ["user_id"])
    op.create_index("ix_drift_run_current_scan_id", "drift_run", ["current_scan_id"])

    # ------------------------------------------------------------------
    # Drift events.
    #
    # ck_drift_event_fact_binding is plan item 3's configuration-versus-evaluation
    # separation expressed as a constraint rather than a convention: a
    # configuration event always names the fact that moved, and an evaluation
    # event never does.
    #
    # The scalar and length CHECKs on previous_value/current_value are the
    # database-level expression of "no raw tenant record is ever stored": an
    # object, an array or anything longer than 120 characters is rejected even if
    # a future bug tries to write one.
    # ------------------------------------------------------------------
    op.create_table(
        "drift_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("drift_run_id", sa.BigInteger(), nullable=False),
        sa.Column("baseline_id", sa.BigInteger(), nullable=False),
        sa.Column("baseline_scan_id", sa.Integer(), nullable=True),
        sa.Column("current_scan_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("control_id", sa.String(50), nullable=False),
        sa.Column("collector_id", sa.String(120), nullable=True),
        sa.Column("event_class", sa.String(20), nullable=False),
        sa.Column("change_type", sa.String(24), nullable=False),
        sa.Column("fact_name", sa.String(40), nullable=True),
        sa.Column("member_ref", sa.String(64), nullable=True),
        sa.Column("previous_value", JSONB(), nullable=True),
        sa.Column("current_value", JSONB(), nullable=True),
        sa.Column("previous_digest", sa.String(64), nullable=True),
        sa.Column("current_digest", sa.String(64), nullable=True),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("severity_basis", sa.String(40), nullable=False),
        sa.Column("event_key", sa.String(64), nullable=False),
        sa.Column("detail", JSONB(), nullable=True),
        sa.Column("correlation_id", sa.String(128), nullable=True),
        sa.Column("drift_version", sa.String(30), nullable=False),
        sa.Column("retention_policy_version", sa.String(40), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["drift_run_id"], ["drift_run.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["baseline_id"], ["drift_baseline.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["baseline_scan_id"], ["scan.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["current_scan_id"], ["scan.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "event_class IN ('configuration','evaluation')",
            name="ck_drift_event_class",
        ),
        sa.CheckConstraint(
            "(event_class = 'configuration') = (fact_name IS NOT NULL)",
            name="ck_drift_event_fact_binding",
        ),
        sa.CheckConstraint(
            "event_class <> 'configuration'"
            " OR change_type IN ('added','removed','changed')",
            name="ck_drift_event_config_change",
        ),
        sa.CheckConstraint(
            "event_class <> 'evaluation'"
            " OR change_type IN ('status_changed','coverage_lost','coverage_gained')",
            name="ck_drift_event_eval_change",
        ),
        sa.CheckConstraint(
            "previous_value IS NULL"
            " OR jsonb_typeof(previous_value) NOT IN ('object','array')",
            name="ck_drift_event_previous_scalar",
        ),
        sa.CheckConstraint(
            "current_value IS NULL"
            " OR jsonb_typeof(current_value) NOT IN ('object','array')",
            name="ck_drift_event_current_scalar",
        ),
        sa.CheckConstraint(
            "previous_value IS NULL OR length(previous_value::text) <= 120",
            name="ck_drift_event_previous_len",
        ),
        sa.CheckConstraint(
            "current_value IS NULL OR length(current_value::text) <= 120",
            name="ck_drift_event_current_len",
        ),
        sa.CheckConstraint(
            "severity IN ('critical','high','medium','low','informational')",
            name="ck_drift_event_severity",
        ),
        sa.CheckConstraint(
            "severity_basis IN ('benchmark_severity','evaluation_transition',"
            "'coverage_loss','observability_change','severity_unavailable')",
            name="ck_drift_event_severity_basis",
        ),
        sa.CheckConstraint(
            "member_ref IS NULL OR member_ref ~ '^[0-9a-f]{64}$'",
            name="ck_drift_event_member_ref",
        ),
        sa.CheckConstraint(
            "event_key ~ '^[0-9a-f]{64}$'",
            name="ck_drift_event_key",
        ),
        sa.CheckConstraint(
            "detail IS NULL OR jsonb_typeof(detail) = 'object'",
            name="ck_drift_event_detail_object",
        ),
    )
    op.create_index(
        "uq_drift_event_run_key",
        "drift_event",
        ["drift_run_id", "event_key"],
        unique=True,
    )
    op.create_index("ix_drift_event_user_id", "drift_event", ["user_id"])
    op.create_index(
        "ix_drift_event_baseline_key", "drift_event", ["baseline_id", "event_key"]
    )

    # ------------------------------------------------------------------
    # Drift notifications: an append-only revision log carrying summary counts
    # and NOTHING else.
    #
    # There is no control id, no fact name, no member ref and no digest column
    # here, so "notifications do not expose sensitive evidence" is true by schema
    # construction rather than by review. Acknowledgement and remediation ride on
    # the revision rows; the current state of a thread is the max-revision row,
    # which is why this table needs no mutable state column and no protect
    # trigger.
    # ------------------------------------------------------------------
    op.create_table(
        "drift_notification",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("baseline_id", sa.BigInteger(), nullable=False),
        sa.Column("drift_run_id", sa.BigInteger(), nullable=True),
        sa.Column("drift_event_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("thread_key", sa.String(64), nullable=False),
        sa.Column("scope", sa.String(10), nullable=False),
        sa.Column("channel", sa.String(20), nullable=False),
        sa.Column("routing_rule", sa.String(40), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(24), nullable=False),
        sa.Column("state_after", sa.String(24), nullable=False),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("summary_code", sa.String(60), nullable=False),
        sa.Column("summary_counts", JSONB(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("verified_run_id", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(128), nullable=True),
        sa.Column("drift_version", sa.String(30), nullable=False),
        sa.Column("retention_policy_version", sa.String(40), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_id"], ["drift_baseline.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["drift_run_id"], ["drift_run.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["drift_event_id"], ["drift_event.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["actor_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["verified_run_id"], ["drift_run.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "scope IN ('event','run')", name="ck_drift_notification_scope"
        ),
        sa.CheckConstraint(
            "channel IN ('inapp')", name="ck_drift_notification_channel"
        ),
        sa.CheckConstraint(
            "routing_rule IN ('owner_high_or_above','owner_coverage_loss',"
            "'owner_not_comparable','owner_fingerprints_unavailable','owner_action')",
            name="ck_drift_notification_routing",
        ),
        sa.CheckConstraint(
            "action IN ('raised','acknowledged','remediation_planned',"
            "'remediation_verified','accepted_risk','superseded')",
            name="ck_drift_notification_action",
        ),
        sa.CheckConstraint(
            "state_after IN ('open','acknowledged','remediation_planned',"
            "'remediation_verified','accepted_risk','superseded')",
            name="ck_drift_notification_state",
        ),
        sa.CheckConstraint(
            "(action = 'raised' AND state_after = 'open')"
            " OR (action <> 'raised' AND state_after = action)",
            name="ck_drift_notification_state_matches_action",
        ),
        sa.CheckConstraint(
            "(action = 'raised') = (revision_number = 1)",
            name="ck_drift_notification_first_revision",
        ),
        sa.CheckConstraint(
            "revision_number >= 1", name="ck_drift_notification_revision_positive"
        ),
        sa.CheckConstraint(
            "(action = 'remediation_verified') = (verified_run_id IS NOT NULL)",
            name="ck_drift_notification_verified",
        ),
        sa.CheckConstraint(
            "note IS NULL OR length(note) <= 1000",
            name="ck_drift_notification_note_length",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(summary_counts) = 'object'",
            name="ck_drift_notification_summary_object",
        ),
        sa.CheckConstraint(
            "severity IN ('critical','high','medium','low','informational')",
            name="ck_drift_notification_severity",
        ),
        sa.CheckConstraint(
            "thread_key ~ '^[0-9a-f]{64}$'",
            name="ck_drift_notification_thread_key",
        ),
        sa.CheckConstraint(
            "(scope = 'event') = (drift_event_id IS NOT NULL OR revision_number > 1)",
            name="ck_drift_notification_event_scope",
        ),
    )
    op.create_index(
        "uq_drift_notification_revision",
        "drift_notification",
        ["thread_key", "revision_number"],
        unique=True,
    )
    op.create_index("ix_drift_notification_user_id", "drift_notification", ["user_id"])
    op.create_index(
        "ix_drift_notification_baseline_id", "drift_notification", ["baseline_id"]
    )

    # ------------------------------------------------------------------
    # Append-only enforcement.
    #
    # These reuse the generic guard created in f7d2c48b1a03, which reads
    # TG_TABLE_NAME and so already covers any table. A second, identical function
    # would only be a second thing to keep in step. The consequence, recorded
    # here deliberately: the exception text reads "Phase 7 drift_event history is
    # append-only". The "Phase 7" in that message names the phase that created
    # the guard, not the phase that owns the table.
    #
    # scan_result_factprint is guarded on UPDATE only. It hangs off the scan by
    # ON DELETE CASCADE, and a DELETE guard would make deleting a scan
    # impossible.
    # ------------------------------------------------------------------
    op.execute("""
        CREATE TRIGGER phase8_factprint_append_only
        BEFORE UPDATE ON scan_result_factprint
        FOR EACH ROW EXECUTE FUNCTION reject_phase7_history_mutation();
    """)
    op.execute("""
        CREATE TRIGGER phase8_drift_run_append_only
        BEFORE UPDATE OR DELETE ON drift_run
        FOR EACH ROW EXECUTE FUNCTION reject_phase7_history_mutation();
    """)
    op.execute("""
        CREATE TRIGGER phase8_drift_event_append_only
        BEFORE UPDATE OR DELETE ON drift_event
        FOR EACH ROW EXECUTE FUNCTION reject_phase7_history_mutation();
    """)
    op.execute("""
        CREATE TRIGGER phase8_drift_notification_append_only
        BEFORE UPDATE OR DELETE ON drift_notification
        FOR EACH ROW EXECUTE FUNCTION reject_phase7_history_mutation();
    """)

    # ------------------------------------------------------------------
    # drift_baseline is the only mutable Phase 8 table: a baseline is superseded
    # or revoked, and carries an operator note. Everything that identifies the
    # observation it was established from is frozen, and a superseded or revoked
    # baseline can never be made active again.
    # ------------------------------------------------------------------
    op.execute("""
        CREATE FUNCTION protect_phase8_drift_baseline() RETURNS trigger AS $$
        BEGIN
            IF ROW(NEW.id, NEW.user_id, NEW.scan_id, NEW.m365_connection_id,
                   NEW.framework, NEW.benchmark, NEW.version, NEW.metadata_digest,
                   NEW.policy_corpus_digest, NEW.semantics_version,
                   NEW.connection_identity_digest, NEW.configuration_key,
                   NEW.evaluation_key, NEW.observation_digest, NEW.control_count,
                   NEW.factprint_field_count, NEW.drift_version,
                   NEW.retention_policy_version, NEW.established_at)
               IS DISTINCT FROM
               ROW(OLD.id, OLD.user_id, OLD.scan_id, OLD.m365_connection_id,
                   OLD.framework, OLD.benchmark, OLD.version, OLD.metadata_digest,
                   OLD.policy_corpus_digest, OLD.semantics_version,
                   OLD.connection_identity_digest, OLD.configuration_key,
                   OLD.evaluation_key, OLD.observation_digest, OLD.control_count,
                   OLD.factprint_field_count, OLD.drift_version,
                   OLD.retention_policy_version, OLD.established_at)
            THEN
                RAISE EXCEPTION 'Phase 8 drift baseline identity is immutable'
                    USING ERRCODE = '23514';
            END IF;
            IF OLD.status IN ('superseded', 'revoked')
               AND NEW.status IS DISTINCT FROM OLD.status
            THEN
                RAISE EXCEPTION 'Phase 8 drift baseline status cannot rewind'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER phase8_drift_baseline_pinned_immutable
        BEFORE UPDATE ON drift_baseline
        FOR EACH ROW EXECUTE FUNCTION protect_phase8_drift_baseline();
    """)

    # protect_phase3_scan_inputs() is deliberately not touched: Phase 8 adds no
    # scan column, and the two new connection fields reach a scan inside the
    # connection_snapshot JSONB the Phase 7 revision already froze.

    # ------------------------------------------------------------------
    # Phase 6 timezone defect: stamp the compared columns in UTC
    # ------------------------------------------------------------------
    # engine/worker/{dispatcher,db,lifecycle}.py now compare against
    # (now() AT TIME ZONE 'UTC'), but these two columns were still STAMPED by a
    # bare now() default. now() is timestamptz; assigning it to a TIMESTAMP
    # WITHOUT TIME ZONE column converts using the server TimeZone, so on a
    # non-UTC server a new dispatch row was stamped ahead of the UTC clock it is
    # compared against and never became due -- the dispatcher published nothing.
    # Verified: backend-api/tests/test_phase4_worker_contract.py failed on an
    # Australia/Melbourne cluster and passed on UTC, before and after this change.
    #
    # These are the only two naive columns compared against a now() expression
    # (scan_dispatch.available_at at dispatcher.py:83,108,126; scan.last_progress_at
    # at dispatcher.py:42,62 as the COALESCE fallback for deadline_at). Converting
    # the schema to timestamptz would change the meaning of existing rows and stays
    # a Phase 6-owned decision; correcting the defaults does not.
    op.execute(
        "ALTER TABLE scan_dispatch ALTER COLUMN available_at "
        "SET DEFAULT (now() AT TIME ZONE 'UTC')"
    )
    op.execute(
        "ALTER TABLE scan ALTER COLUMN last_progress_at "
        "SET DEFAULT (now() AT TIME ZONE 'UTC')"
    )


def downgrade() -> None:
    raise RuntimeError(
        "Phase 8 drift evidence and the Purview binding are forward-only; "
        "restore from a verified backup instead."
    )
