"""Phase 9: the durable unit of work becomes a collection, not a control.

Adds ``scan_dispatch.collector_id`` and the CHECK that makes a dispatch row's
three shapes structural rather than conventional:

* neither identifier  -> the scan's own ``run_scan`` row;
* ``collector_id``    -> one collection group, fanned out to every ready control
                         that names that collector;
* ``result_id``       -> one control, the Phase 6 shape, still accepted so an
                         outbox row written before this deploy is not stranded.

Nullable and without a server default: existing rows are control rows and must
stay control rows. Nothing here changes a result, a score or a rating.

Written by hand rather than autogenerated: alembic/env.py configures neither
compare_type nor compare_server_default, so autogenerate cannot see the CHECK or
the partial index below.

Forward-only, consistent with Phase 3/5/6/7/8.

Revision ID: b9d4e17c6a52
Revises: a3f5c1d90b47
"""

import sqlalchemy as sa
from alembic import op

revision = "b9d4e17c6a52"
down_revision = "a3f5c1d90b47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "scan_dispatch",
        sa.Column("collector_id", sa.String(200), nullable=True),
    )
    # A row is keyed by one discriminator at most. Without this a future writer
    # could produce a row that publishes as a collection AND cascades away with
    # a single result, which is two different lifetimes for one row.
    op.execute("""
        ALTER TABLE scan_dispatch ADD CONSTRAINT ck_scan_dispatch_single_key
        CHECK (result_id IS NULL OR collector_id IS NULL)
    """)
    # The reconciler and the publisher both look up a scan's collection rows.
    # Partial, because control rows and run_scan rows never match this predicate.
    op.execute("""
        CREATE INDEX ix_scan_dispatch_collection ON scan_dispatch (scan_id, collector_id)
        WHERE collector_id IS NOT NULL
    """)

    # Phase 3's immutability trigger covers scan input columns only; scan_dispatch
    # is orchestration state and is deliberately outside it. No trigger changes.


def downgrade() -> None:
    raise RuntimeError(
        "Phase 9 collection dispatch is forward-only; restore from a verified "
        "backup instead."
    )
